/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;
import Modelo.Aluno;
import Modelo.Curso;
import Modelo.Disciplina;
import Modelo.Professor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class NewJFrame extends javax.swing.JFrame {
    ArrayList<String> alunosCadastrados = new ArrayList<String>();
    ArrayList<String> disciplinasCadastradas = new ArrayList<String>();
    ArrayList<String> cursosCadastrados = new ArrayList<String>();
    ArrayList<String> professoresCadastrados = new ArrayList<String>();
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonCancelarAluno = new javax.swing.JButton();
        ButtonCadastrarAluno = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextFieldNomeAluno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextFieldCpfAluno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextFieldMatricula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TextFieldCursoAluno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxSexoAluno = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        ButtonLimparAluno = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        ButtonTodosAlunos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ButtonCadastroProf = new javax.swing.JButton();
        ButtonCancelarProf = new javax.swing.JButton();
        ButtonLimparProf = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TextFieldNomeProfessor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TextFieldRegistroProfessor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TextFieldCpfProfessor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TextFieldDeptProfessor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ComboBoxSexoProfessor = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ButtonTodosProfessores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ButtonCadastraCurso = new javax.swing.JButton();
        ButtonLimpaCurso = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        TextFieldNomeCurso = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        TextFieldDeptCurso = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        ButtonCancelaCurs = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jSpinner11 = new javax.swing.JSpinner();
        jLabel38 = new javax.swing.JLabel();
        jSpinner12 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        ButtonTodosCursos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ButtonCadstraDisci = new javax.swing.JButton();
        ButtonCancelaDisci = new javax.swing.JButton();
        ButtonLimpaDisci = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        TextFieldNomeDisciplina = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        TextFieldDeptDisciplina = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jSpinner13 = new javax.swing.JSpinner();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        TextFieldProfDisciplina = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        TextFieldCoDisciplina = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ButtonTodasDisci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRO DE ALUNOS");

        ButtonCancelarAluno.setText("Cancelar");
        ButtonCancelarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCancelarAlunoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonCancelarAlunoMousePressed(evt);
            }
        });
        ButtonCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarAlunoActionPerformed(evt);
            }
        });

        ButtonCadastrarAluno.setText("Cadastrar");
        ButtonCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarAlunoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome:");

        TextFieldNomeAluno.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                TextFieldNomeAlunoAncestorRemoved(evt);
            }
        });
        TextFieldNomeAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextFieldNomeAlunoMousePressed(evt);
            }
        });
        TextFieldNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeAlunoActionPerformed(evt);
            }
        });
        TextFieldNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldNomeAlunoKeyTyped(evt);
            }
        });

        jLabel6.setText("CPF:");

        jLabel7.setText("Matrícula:");

        TextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldMatriculaActionPerformed(evt);
            }
        });

        jLabel8.setText("Data de Nascimento: ");

        jLabel9.setText("Curso:");

        TextFieldCursoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCursoAlunoActionPerformed(evt);
            }
        });

        jLabel10.setText("Sexo");

        ComboBoxSexoAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));
        ComboBoxSexoAluno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxSexoAlunoItemStateChanged(evt);
            }
        });
        ComboBoxSexoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSexoAlunoActionPerformed(evt);
            }
        });

        jLabel11.setText("Dia");

        jLabel12.setText("Mês");

        jLabel13.setText("Ano");

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1900, null, 2016, 1));
        jSpinner3.setValue(2016);

        ButtonLimparAluno.setText("Limpar");
        ButtonLimparAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparAlunoActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        ButtonTodosAlunos.setText("Alunos Cadastrados");
        ButtonTodosAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTodosAlunosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxSexoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldCursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(ButtonCancelarAluno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonCadastrarAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonLimparAluno))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(12, 12, 12)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel13)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonTodosAlunos)
                                .addGap(59, 59, 59))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextFieldCursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxSexoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TextFieldCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastrarAluno)
                    .addComponent(ButtonCancelarAluno)
                    .addComponent(ButtonLimparAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonTodosAlunos)
                .addGap(15, 15, 15))
        );

        jTabbedPane2.addTab("ALUNO", jPanel1);

        ButtonCadastroProf.setText("Cadastar");
        ButtonCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastroProfActionPerformed(evt);
            }
        });

        ButtonCancelarProf.setText("Cancelar");
        ButtonCancelarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarProfActionPerformed(evt);
            }
        });

        ButtonLimparProf.setText("Limpar");
        ButtonLimparProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparProfActionPerformed(evt);
            }
        });

        jLabel15.setText("Nome:");

        TextFieldNomeProfessor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                TextFieldNomeProfessorAncestorRemoved(evt);
            }
        });
        TextFieldNomeProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextFieldNomeProfessorMousePressed(evt);
            }
        });
        TextFieldNomeProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeProfessorActionPerformed(evt);
            }
        });

        jLabel16.setText("Registro:");

        TextFieldRegistroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRegistroProfessorActionPerformed(evt);
            }
        });

        jLabel17.setText("CPF:");

        jLabel18.setText("Departamento:");

        TextFieldDeptProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDeptProfessorActionPerformed(evt);
            }
        });

        jLabel19.setText("Sexo");

        ComboBoxSexoProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Feminino", "Masculino" }));
        ComboBoxSexoProfessor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxSexoProfessorItemStateChanged(evt);
            }
        });

        jLabel20.setText("Data de Nascimento: ");

        jLabel21.setText("Dia");

        jLabel22.setText("Mês");

        jLabel23.setText("Ano");

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2016, 1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setText("CADASTRO DE PROFESSORES");

        ButtonTodosProfessores.setText("Professores Cadastrados");
        ButtonTodosProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTodosProfessoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldCpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboBoxSexoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ButtonCancelarProf))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(163, 163, 163)
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(ButtonCadastroProf)
                                                    .addComponent(jLabel20))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel21)
                                                        .addGap(15, 15, 15)
                                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(56, 56, 56)
                                                        .addComponent(ButtonLimparProf))))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldRegistroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldDeptProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(162, 162, 162))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonTodosProfessores)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TextFieldNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TextFieldRegistroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TextFieldDeptProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(TextFieldCpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxSexoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastroProf)
                    .addComponent(ButtonLimparProf)
                    .addComponent(ButtonCancelarProf))
                .addGap(18, 18, 18)
                .addComponent(ButtonTodosProfessores)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("PROFESSOR", jPanel2);

        ButtonCadastraCurso.setText("Cadastrar");
        ButtonCadastraCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastraCursoActionPerformed(evt);
            }
        });

        ButtonLimpaCurso.setText("Limpar");
        ButtonLimpaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpaCursoActionPerformed(evt);
            }
        });

        jLabel29.setText("Nome do Curso:");

        TextFieldNomeCurso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                TextFieldNomeCursoAncestorRemoved(evt);
            }
        });
        TextFieldNomeCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextFieldNomeCursoMousePressed(evt);
            }
        });
        TextFieldNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeCursoActionPerformed(evt);
            }
        });

        jLabel35.setText("Departamento:");

        jLabel36.setText("Natureza:");

        jCheckBox1.setText("Teórica");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Prática");

        ButtonCancelaCurs.setText("Cancelar");
        ButtonCancelaCurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelaCursActionPerformed(evt);
            }
        });

        jLabel37.setText("Duração (Anos):");

        jSpinner11.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel38.setText("Quantidade de matérias: ");

        jSpinner12.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 1));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel24.setText("CADASTRO DE CURSOS");

        ButtonTodosCursos.setText("Cursos Cadastrados");
        ButtonTodosCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTodosCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ButtonCancelaCurs)
                                .addGap(71, 71, 71)
                                .addComponent(ButtonCadastraCurso)
                                .addGap(87, 87, 87)
                                .addComponent(ButtonLimpaCurso))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TextFieldNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox2)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel37))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jSpinner11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(TextFieldDeptCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonTodosCursos)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(TextFieldDeptCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jSpinner11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(TextFieldNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel36)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadastraCurso)
                    .addComponent(ButtonCancelaCurs)
                    .addComponent(ButtonLimpaCurso))
                .addGap(18, 18, 18)
                .addComponent(ButtonTodosCursos)
                .addGap(34, 34, 34))
        );

        jTabbedPane2.addTab("CURSO", jPanel3);

        ButtonCadstraDisci.setText("Cadastrar");
        ButtonCadstraDisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadstraDisciActionPerformed(evt);
            }
        });

        ButtonCancelaDisci.setText("Cancelar");
        ButtonCancelaDisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelaDisciActionPerformed(evt);
            }
        });

        ButtonLimpaDisci.setText("Limpar");
        ButtonLimpaDisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpaDisciActionPerformed(evt);
            }
        });

        jLabel39.setText("Nome da Disciplina:");

        TextFieldNomeDisciplina.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                TextFieldNomeDisciplinaAncestorRemoved(evt);
            }
        });
        TextFieldNomeDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextFieldNomeDisciplinaMousePressed(evt);
            }
        });
        TextFieldNomeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeDisciplinaActionPerformed(evt);
            }
        });

        jLabel40.setText("Departamento:");

        jLabel41.setText("Natureza:");

        jCheckBox3.setText("Teórica");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Prática");

        jSpinner13.setModel(new javax.swing.SpinnerNumberModel(8, null, 100, 1));

        jLabel42.setText("Duração (Horas):");

        jLabel45.setText("Professor responsável:");

        jLabel44.setText("Código:");

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel25.setText("CADASTRO DE DISCIPLINAS");

        ButtonTodasDisci.setText("Disciplinas Cadastradas");
        ButtonTodasDisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTodasDisciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel41))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3)
                                    .addComponent(TextFieldCoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldDeptDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(ButtonCancelaDisci)
                        .addGap(56, 56, 56)
                        .addComponent(ButtonCadstraDisci)
                        .addGap(62, 62, 62)
                        .addComponent(ButtonLimpaDisci)))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel42))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldProfDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(ButtonTodasDisci)
                        .addGap(71, 71, 71))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(TextFieldNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(TextFieldDeptDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel45)
                    .addComponent(TextFieldProfDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(TextFieldCoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadstraDisci)
                    .addComponent(ButtonLimpaDisci)
                    .addComponent(ButtonCancelaDisci))
                .addGap(26, 26, 26)
                .addComponent(ButtonTodasDisci)
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("DISCIPLINA", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancelarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCancelarAlunoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancelarAlunoMouseClicked

    private void ButtonCancelarAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCancelarAlunoMousePressed

    }//GEN-LAST:event_ButtonCancelarAlunoMousePressed

    private void ButtonCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarAlunoActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar a operação? ") == 0){
            JOptionPane.showMessageDialog(null,"Operação Cancelada");
            this.dispose();
        }
    }//GEN-LAST:event_ButtonCancelarAlunoActionPerformed

    private void ButtonCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarAlunoActionPerformed
        Aluno aluno = new Aluno();
        String nome,matricula,curso;
        try{
            nome = TextFieldNomeAluno.getText();
            curso = TextFieldCursoAluno.getText();
            matricula = TextFieldMatricula.getText();

            aluno.setNome(nome);
            aluno.setMatricula(matricula);
            aluno.setCurso(curso);

            alunosCadastrados.add("Aluno: "+aluno.getNome()+"\nMatrícula: "+aluno.getMatricula()+"\nCurso: "+aluno.getCurso()+"\n\n");

            JOptionPane.showMessageDialog(null,"Aluno(a) cadastrado com sucesso!");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Falhou");
        }

        TextFieldNomeAluno.setText("");
        TextFieldCpfAluno.setText("");
        TextFieldMatricula.setText("");
        TextFieldCursoAluno.setText("");
        jSpinner3.setValue(1900);
    }//GEN-LAST:event_ButtonCadastrarAlunoActionPerformed

    private void TextFieldNomeAlunoAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextFieldNomeAlunoAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeAlunoAncestorRemoved

    private void TextFieldNomeAlunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNomeAlunoMousePressed

    }//GEN-LAST:event_TextFieldNomeAlunoMousePressed

    private void TextFieldNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeAlunoActionPerformed

    }//GEN-LAST:event_TextFieldNomeAlunoActionPerformed

    private void TextFieldNomeAlunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldNomeAlunoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeAlunoKeyTyped

    private void TextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldMatriculaActionPerformed

    private void TextFieldCursoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCursoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCursoAlunoActionPerformed

    private void ComboBoxSexoAlunoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxSexoAlunoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxSexoAlunoItemStateChanged

    private void ComboBoxSexoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxSexoAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxSexoAlunoActionPerformed

    private void ButtonLimparAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparAlunoActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Todas as informações serão PERDIDAS. Deseja LIMPAR o formulário?") == 0){
            TextFieldNomeAluno.setText("");
            TextFieldCpfAluno.setText("");
            TextFieldMatricula.setText("");
            TextFieldCursoAluno.setText("");
            jSpinner3.setValue(0);
        }
    }//GEN-LAST:event_ButtonLimparAlunoActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void ButtonTodosAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTodosAlunosActionPerformed
        if(alunosCadastrados.isEmpty())
        JOptionPane.showMessageDialog(null,"Nenhum aluno foi cadastrado ainda");
        else
        JOptionPane.showMessageDialog(null,alunosCadastrados);
    }//GEN-LAST:event_ButtonTodosAlunosActionPerformed

    private void ButtonCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastroProfActionPerformed
        Professor professor = new Professor();
        String nome,departamento;
        int registro;
        nome = TextFieldNomeProfessor.getText();
        registro = Integer.parseInt(TextFieldRegistroProfessor.getText());
        departamento = TextFieldDeptProfessor.getText();

        professor.setNome(nome);
        professor.setRegistro(registro);
        professor.setDepartamento(departamento);

        professoresCadastrados.add("Professor: "+professor.getNome()+"\nRegistro: "+professor.getRegistro()+"\nDepartamento: "+professor.getDepartamento()+"\n\n");
        JOptionPane.showMessageDialog(null,"Professor(a) cadastrado com sucesso!");

        TextFieldNomeProfessor.setText("");
        TextFieldCpfProfessor.setText("");
        TextFieldRegistroProfessor.setText("");
        TextFieldDeptProfessor.setText("");
        jSpinner3.setValue(1900);
    }//GEN-LAST:event_ButtonCadastroProfActionPerformed

    private void ButtonCancelarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarProfActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar a operação? ") == 0){
            JOptionPane.showMessageDialog(null,"Operação Cancelada");
            this.dispose();
        }
    }//GEN-LAST:event_ButtonCancelarProfActionPerformed

    private void ButtonLimparProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparProfActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Todas as informações serão PERDIDAS.Deseja LIMPAR o formulário?") == 0){
            TextFieldNomeProfessor.setText("");
            TextFieldRegistroProfessor.setText("");
            TextFieldCpfProfessor.setText("");
            TextFieldDeptProfessor.setText("");
            jSpinner6.setValue(0);
        }
    }//GEN-LAST:event_ButtonLimparProfActionPerformed

    private void TextFieldNomeProfessorAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextFieldNomeProfessorAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeProfessorAncestorRemoved

    private void TextFieldNomeProfessorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNomeProfessorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeProfessorMousePressed

    private void TextFieldNomeProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeProfessorActionPerformed

    private void TextFieldRegistroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRegistroProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRegistroProfessorActionPerformed

    private void TextFieldDeptProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDeptProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDeptProfessorActionPerformed

    private void ComboBoxSexoProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxSexoProfessorItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxSexoProfessorItemStateChanged

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void ButtonTodosProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTodosProfessoresActionPerformed
        if(professoresCadastrados.isEmpty())
        JOptionPane.showMessageDialog(null,"Nenhum professor foi cadastrado ainda");
        else
        JOptionPane.showMessageDialog(null,professoresCadastrados);
    }//GEN-LAST:event_ButtonTodosProfessoresActionPerformed

    private void ButtonCadastraCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastraCursoActionPerformed
        Curso curso = new Curso();
        String nome,departamento;
        nome = TextFieldNomeCurso.getText();
        departamento = TextFieldDeptCurso.getText();

        curso.setNome(nome);
        curso.setDepartamento(departamento);

        cursosCadastrados.add("Curso: "+curso.getNome()+"\nDepartamento: "+curso.getDepartamento()+"\n\n");
        JOptionPane.showMessageDialog(null,"Curso cadastrado com sucesso!");

        TextFieldNomeCurso.setText("");
        TextFieldDeptCurso.setText("");
        jSpinner11.setValue(0);
        jSpinner12.setValue(0);
    }//GEN-LAST:event_ButtonCadastraCursoActionPerformed

    private void ButtonLimpaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpaCursoActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Todas as informações serão PERDIDAS.Deseja LIMPAR o formulário?") == 0){
            TextFieldNomeCurso.setText("");
            TextFieldDeptCurso.setText("");
            jSpinner11.setValue(0);
            jSpinner12.setValue(0);
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
        }
    }//GEN-LAST:event_ButtonLimpaCursoActionPerformed

    private void TextFieldNomeCursoAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextFieldNomeCursoAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeCursoAncestorRemoved

    private void TextFieldNomeCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNomeCursoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeCursoMousePressed

    private void TextFieldNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeCursoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void ButtonCancelaCursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelaCursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancelaCursActionPerformed

    private void ButtonTodosCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTodosCursosActionPerformed
        if(cursosCadastrados.isEmpty())
        JOptionPane.showMessageDialog(null,"Nenhum curso foi cadastrado ainda");
        else
        JOptionPane.showMessageDialog(null,cursosCadastrados);
    }//GEN-LAST:event_ButtonTodosCursosActionPerformed

    private void ButtonCadstraDisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadstraDisciActionPerformed
        Disciplina disci = new Disciplina();
        String nome;
        int cod;
        nome = TextFieldNomeDisciplina.getText();
        cod = Integer.parseInt(TextFieldCoDisciplina.getText());

        disci.setNome(nome);
        disci.setCod(cod);

        alunosCadastrados.add("Disciplina: "+disci.getNome()+"\nCódigo: "+disci.getCod()+"\n\n");
        JOptionPane.showMessageDialog(null,"Disciplina cadastrado com sucesso!");

        TextFieldNomeDisciplina.setText("");
        TextFieldDeptDisciplina.setText("");
        TextFieldCoDisciplina.setText("");
        TextFieldProfDisciplina.setText("");
        jSpinner13.setValue(0);
    }//GEN-LAST:event_ButtonCadstraDisciActionPerformed

    private void ButtonCancelaDisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelaDisciActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar a operação? ") == 0){
            JOptionPane.showMessageDialog(null,"Operação Cancelada");
            this.dispose();
        }
    }//GEN-LAST:event_ButtonCancelaDisciActionPerformed

    private void ButtonLimpaDisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpaDisciActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Todas as informações serão PERDIDAS.Deseja LIMPAR o formulário?") == 0){
            TextFieldNomeDisciplina.setText("");
            TextFieldDeptDisciplina.setText("");
            TextFieldCoDisciplina.setText("");
            TextFieldProfDisciplina.setText("");
            jSpinner13.setValue(0);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
        }
    }//GEN-LAST:event_ButtonLimpaDisciActionPerformed

    private void TextFieldNomeDisciplinaAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TextFieldNomeDisciplinaAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeDisciplinaAncestorRemoved

    private void TextFieldNomeDisciplinaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNomeDisciplinaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeDisciplinaMousePressed

    private void TextFieldNomeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeDisciplinaActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void ButtonTodasDisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTodasDisciActionPerformed
        if(disciplinasCadastradas.isEmpty())
        JOptionPane.showMessageDialog(null,"Nenhuma disciplina foi cadastrada ainda");
        else
        JOptionPane.showMessageDialog(null,disciplinasCadastradas);
    }//GEN-LAST:event_ButtonTodasDisciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastraCurso;
    private javax.swing.JButton ButtonCadastrarAluno;
    private javax.swing.JButton ButtonCadastroProf;
    private javax.swing.JButton ButtonCadstraDisci;
    private javax.swing.JButton ButtonCancelaCurs;
    private javax.swing.JButton ButtonCancelaDisci;
    private javax.swing.JButton ButtonCancelarAluno;
    private javax.swing.JButton ButtonCancelarProf;
    private javax.swing.JButton ButtonLimpaCurso;
    private javax.swing.JButton ButtonLimpaDisci;
    private javax.swing.JButton ButtonLimparAluno;
    private javax.swing.JButton ButtonLimparProf;
    private javax.swing.JButton ButtonTodasDisci;
    private javax.swing.JButton ButtonTodosAlunos;
    private javax.swing.JButton ButtonTodosCursos;
    private javax.swing.JButton ButtonTodosProfessores;
    private javax.swing.JComboBox<String> ComboBoxSexoAluno;
    private javax.swing.JComboBox<String> ComboBoxSexoProfessor;
    private javax.swing.JTextField TextFieldCoDisciplina;
    private javax.swing.JTextField TextFieldCpfAluno;
    private javax.swing.JTextField TextFieldCpfProfessor;
    private javax.swing.JTextField TextFieldCursoAluno;
    private javax.swing.JTextField TextFieldDeptCurso;
    private javax.swing.JTextField TextFieldDeptDisciplina;
    private javax.swing.JTextField TextFieldDeptProfessor;
    private javax.swing.JTextField TextFieldMatricula;
    private javax.swing.JTextField TextFieldNomeAluno;
    private javax.swing.JTextField TextFieldNomeCurso;
    private javax.swing.JTextField TextFieldNomeDisciplina;
    private javax.swing.JTextField TextFieldNomeProfessor;
    private javax.swing.JTextField TextFieldProfDisciplina;
    private javax.swing.JTextField TextFieldRegistroProfessor;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
